version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: balldev1
      MONGO_INITDB_PASSWORD: balldev1
    ports:
      - 27023:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:


# docker-compose up -d
# docker exec -it mongodb mongosh
# docker images
# docker ps
# docker ps -a
# mongodb://root:example@localhost:27023

